apiVersion: v1
kind: Namespace
metadata:
  name: image-cloner-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: image-cloner-config
  namespace: image-cloner-system
data:
  IMAGE_CLONER_REGISTRY: 192.168.1.128:5000
  IMAGE_CLONER_SKIP_NAMESPACES: image-cloner-system
---
apiVersion: v1
kind: Secret
metadata:
  name: image-cloner-cr-login
  namespace: image-cloner-system
data:
  IMAGE_CLONER_USER: dGVzdHVzZXI=
  IMAGE_CLONER_PASS: dGVzdHBhc3M=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-cloner
  namespace: image-cloner-system
  labels:
    app: image-cloner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-cloner
  template:
    metadata:
      labels:
        app: image-cloner
    spec:
      serviceAccount: image-cloner
      containers:
      - name: image-cloner
        image: ghcr.io/lucasepe/image-cloner:0.1.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: image-cloner-config
        - secretRef:
            name: image-cloner-cr-login