apiVersion: v1
kind: Namespace
metadata:
  name: image-cloner-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-cloner
  namespace: image-cloner-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-cloner-role
  namespace: image-cloner-system
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-cloner-role-binding
  namespace: image-cloner-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-cloner-role
subjects:
- kind: ServiceAccount
  name: image-cloner
  namespace: image-cloner-system
